# Generated by Django 4.2.6 on 2023-11-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsh', '0004_cartitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='customer',
        ),
    ]
