# Generated by Django 4.2.6 on 2023-11-06 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsh', '0005_rename_user_cartitem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Engine Parts', 'Engine Parts'), ('Electrical Parts', 'Electrical Parts'), ('Suspension and Steering', 'Suspension and Steering'), ('Transmission and Drivetrain', 'Transmission and Drivetrain'), ('Body and Frame', 'Body and Frame'), ('Accessories', 'Accessories'), ('Performance Upgrades', 'Performance Upgrades'), ('Maintenance and Care', 'Maintenance and Care'), ('Oils and Lubricants', 'Oils and Lubricants')], default='Engine Parts', max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='jsh.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
